### ISSUE TITLE
Crash on 24-12-17 at 07:35:56 

### ISSUE THREAD

**Issue by tannerkrewson** [tannerkrewson/drawphone#17]
```
Dec 24 07:35:56 drawphone app/web.1:  /app/routes/socketio.js:38 
Dec 24 07:35:56 drawphone app/web.1:  			var thisRound = thisGame.currentRound; 
Dec 24 07:35:56 drawphone app/web.1:  			                         ^ 
Dec 24 07:35:56 drawphone app/web.1:  TypeError: Cannot read property 'currentRound' of undefined 
Dec 24 07:35:56 drawphone app/web.1:      at Socket.<anonymous> (/app/routes/socketio.js:38:29) 
Dec 24 07:35:56 drawphone app/web.1:      at emitOne (events.js:116:13) 
Dec 24 07:35:56 drawphone app/web.1:      at Socket.emit (events.js:211:7) 
Dec 24 07:35:56 drawphone app/web.1:      at /app/node_modules/socket.io/lib/socket.js:513:12 
Dec 24 07:35:56 drawphone app/web.1:      at _combinedTickCallback (internal/process/next_tick.js:131:7) 
Dec 24 07:35:56 drawphone app/web.1:      at process._tickCallback (internal/process/next_tick.js:180:9) 
Dec 24 07:35:57 drawphone app/web.1:  npm ERR! A complete log of this run can be found in: 
Dec 24 07:35:57 drawphone app/web.1:  npm ERR!     /app/.npm/_logs/2017-12-24T15_35_56_258Z-debug.log 
Dec 24 07:36:00 drawphone app/web.1:  npm ERR! code ELIFECYCLE 
Dec 24 07:36:00 drawphone app/web.1:  npm ERR! errno 1 
Dec 24 07:36:00 drawphone app/web.1:  npm ERR! drawphone@1.0.0 start: `node ./bin/www` 
Dec 24 07:36:00 drawphone app/web.1:  npm ERR! Exit status 1 
Dec 24 07:36:00 drawphone app/web.1:  npm ERR!  
Dec 24 07:36:00 drawphone app/web.1:  npm ERR! Failed at the drawphone@1.0.0 start script. 
Dec 24 07:36:00 drawphone app/web.1:  npm ERR! This is probably not a problem with npm. There is likely additional logging output above. 
```

This crash also occurred once the day before.

**Comment by tannerkrewson** [comment]
I guess it's fixed 🤷‍♀️ 

https://github.com/tannerkrewson/drawphone/pull/18
