### ISSUE TITLE
12-28-19 crash

### ISSUE THREAD

**Issue by tannerkrewson** [tannerkrewson/drawphone#28]
```
2019-12-28T09:55:30.228085405Z app[web.1]: /app/routes/socketio.js:30
2019-12-28T09:55:30.228141776Z app[web.1]:                      if (data.timeLimit !== false && thisUser.isAdmin) {
2019-12-28T09:55:30.228164447Z app[web.1]:                                                               ^
2019-12-28T09:55:30.228174528Z app[web.1]:
2019-12-28T09:55:30.228183185Z app[web.1]: TypeError: Cannot read property 'isAdmin' of undefined
2019-12-28T09:55:30.228192285Z app[web.1]:     at Socket.<anonymous> (/app/routes/socketio.js:30:45)
2019-12-28T09:55:30.228201909Z app[web.1]:     at Socket.emit (events.js:198:13)
2019-12-28T09:55:30.228210796Z app[web.1]:     at /app/node_modules/socket.io/lib/socket.js:528:12
2019-12-28T09:55:30.228219921Z app[web.1]:     at process._tickCallback (internal/process/next_tick.js:61:11)
2019-12-28T09:55:30.255232653Z app[web.1]: npm ERR! code ELIFECYCLE
2019-12-28T09:55:30.256389631Z app[web.1]: npm ERR! errno 1
2019-12-28T09:55:30.258940992Z app[web.1]: npm ERR! drawphone@1.0.0 start: `node ./bin/www`
2019-12-28T09:55:30.259418681Z app[web.1]: npm ERR! Exit status 1
2019-12-28T09:55:30.259875921Z app[web.1]: npm ERR!
2019-12-28T09:55:30.260161529Z app[web.1]: npm ERR! Failed at the drawphone@1.0.0 start script.
2019-12-28T09:55:30.260426167Z app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-12-28T09:55:30.283470444Z app[web.1]:
2019-12-28T09:55:30.284646895Z app[web.1]: npm ERR! A complete log of this run can be found in:
2019-12-28T09:55:30.285260390Z app[web.1]: npm ERR!     /app/.npm/_logs/2019-12-28T09_55_30_261Z-debug.log
2019-12-28T09:55:33.333532085Z app[web.1]:
2019-12-28T09:55:33.333613008Z app[web.1]: > drawphone@1.0.0 start /app
2019-12-28T09:55:33.333617424Z app[web.1]: > node ./bin/www
```

also, going to `drawphone.tannerkrewson.com` right now gives me cloudflare 502

**Comment by tannerkrewson** [comment]
don't really know why that error would have ever happened. but this fixes it. not sure why cloudflare was 502, because dokku auto restarts on crash
